### ISSUE TITLE
Is this repo a work in progress?

### ISSUE THREAD

**Issue by TheMcMurder** [esm-bundle/mui-datatables#10]
This appears to be a WIP. I made the changes necessary to fix the build not realizing it was a WIP. The changes should work when the rest of the repo is finished.

**Comment by internettrans** [comment]
Yes see https://github.com/esm-bundle/new-repo-instructions/issues/12

**Comment by princed** [comment]
I am very sorry, but I'm not going to proceed with this repo. Two reasons:
* it turned out to be really hard if not impossible to convert the original minified babel-compiled npm package into a proper ESM. And if I remember correctly the use of `pnpm` made it even more challenging 😢  
* a bug `esbuild` that prompted this package has been since fixed.

Please feel free to delete the repo and thank you again for the great initiative!
